openapi: 3.0.0
info:
  title: StartUpCRM API
  description: API для приема и обработки заказов
  contact:
    email: alexander.gardner.g@gmail.com
  version: 1.0.5
servers:
  - url: http://localhost:10100/smartpay/v1
    description: SwaggerHub API Auto Mocking
security:
  - bearerAuth: []
tags:
  - name: payments
    description: Платежные операции
  - name: callback
    description: Callback от платежного оператора
  - name: cards
    description: Операции с карточными связками
paths:
  /orders/placeorder:
    post:
      tags:
        - placeorder
      summary: Создать заказ
      description: |
        Создать заказ для клиента.
      operationId: placeOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/placeorder'
      responses:
        "200":
          description: Идентификатор созданного счета
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/base_response'
        "400":
          description: bad input parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/base_response'
        "401":
          description: Access token is missing or invalid
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/base_response'

  /operator/openorders:
    get:
      tags:
        - openorders
      summary: Список открытых заказов оператора
      description: |
        Получить список открытых заказов оператора
      operationId: getOpenOrders
      parameters:
        - name: page
          in: query
          schema:
            type: integer
        - name: itemsPerPage
          in: query
          schema:
            type: integer
      responses:
        "200":
          description: Список открытых заказов оператора
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/openorderslist'
        "400":
          description: bad input parameter
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/base_response'
        "401":
          description: Access token is missing or invalid
        default:
          description: Unauthorised
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/base_response'

components:
  schemas:
    openorderslist:
      allOf:
        - $ref: '#/components/schemas/base_response'
        - $ref: '#/components/schemas/openorders'
    openorder:
      type: object
      properties:
        orders_user_id:
          type: integer
        name:
          type: string
        purchase_name:
          type: string
        "id":
          type: integer
        "city":
          type: string
        "street":
          type: string
        "building":
           type: string
        "flat":
          type: string
        "deliverydate":
          type: string
        "created_at":
          type: string
        "status":
          type: integer
    openorders:
      type: object
      properties:
        cards:
          type: array
          items:
            allOf:
              - $ref: '#/components/schemas/openorder'
    error1:
      type: object
      properties:
        message:
          type: string
        description:
          type: string
        code:
          type: integer
    error:
      type: object
      properties:
        error:
          $ref: '#/components/schemas/error1'
    base_response:
      $ref: '#/components/schemas/error'
    placeorder:
      type: object
      properties:
        "name":
          type: string
        "surName":
          type: string
        "lastName":
          type: string
        "purchaseName":
          type: string
        "city":
          type: string
        "street":
          type: string
        "building":
          type: string
        "flat":
          type: string
        "phone":
          type: string
        "deliveryDate":
          type: string
        "email":
          type: string
    access_token:
      type: object
      properties:
        token:
          type: string
          description: access token пользователя в формате Bearer <token>
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
    basicAuth:
      type: http
      scheme: basic
